### ISSUE TITLE
display username on home page when logged in

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/persona.fm#148]

**Comment by parthib2004** [comment]
Hello can you please assign this issue to me?

**Comment by Jash2606** [comment]
Hey @raspberri05 ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by bulutyerli** [comment]
> Hey @raspberri05 , I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

@parthib2004 already asked for assignment. You should not ask after him.

**Comment by raspberri05** [comment]
Hi @parthib2004 . Since you were the first one to request assignment of this issue, I will be assigning this issue to you. @Jash2606 and @bulutyerli, there are other issues in this repository that you could be assigned to since this one is taken. I also have a couple of other repos in my profile that are looking for contributors so feel free to check out the issue in those as well. Thanks
