### ISSUE TITLE
add groups to db schema

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/persona.fm#190]
groups table:
id: uuid
name: text

group memberships table (join table)
user_id: references user.uid
group_id: references group.uid

**Comment by Humayun-23** [comment]
Please assign this task to me

**Comment by raspberri05** [comment]
Done! If you need any help, feel free to ask or to consult https://orm.drizzle.team/docs/overview

**Comment by Humayun-23** [comment]
![Screenshot from 2024-10-21 17-44-06](https://github.com/user-attachments/assets/b81c6de5-6ada-4ccc-a5ee-168650cc9f17)
I am getting this error
