### ISSUE TITLE
add linting ci test

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/persona.fm#194]
eslint (take from raspberri05/raspberri05.github.io

**Comment by mashazyu** [comment]
@raspberri05 ,

If this issue is up for grabs, I 'd like to work on it.

**Comment by raspberri05** [comment]
Great! You can use this as a starting point 
https://github.com/raspberri05/raspberri05.github.io/blob/main/.github/workflows/eslint.yml
You'll have to make changes so that it only runs in the application/ subdirectory
